#!/bin/bash

FONTS_HOME=$HOME/.local/share/fonts
if [ ! -d "$FONTS_HOME" ]; then
    mkdir -p "$FONTS_HOME"
fi

install_fonts_arch() {
    if ! command -v yay &> /dev/null; then
        sudo pacman -S --needed base-devel git
        if [ ! -d "$HOME/git" ]; then
            mkdir "$HOME/git"
        fi
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si
        cd ..
    fi
    if ! yay -Qs nerd-fonts-fira-code > /dev/null; then
        yay ttf-fira-code
    else
        echo "FiraCode is already installed via yay"
    fi

    if ! yay -Qs nerd-fonts-meslo > /dev/null; then
        yay ttf-meslo-nerd
    else
        echo "Meslo is already installed via yay"
    fi

    if ! yay -Qs ttf-font-awesome > /dev/null; then
        yay ttf-font-awesome
    else
        echo "FontAwesome is already installed via yay"
    fi
}

install_fonts_manual() {
    cd ~/Downloads
    # Check if FiraCode is installed
    if [ ! -f "$FONTS_HOME/FiraCode-Regular.ttf" ]; then
        wget https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip
        unzip FiraCode.zip -d $FONTS_HOME
        rm FiraCode.zip
    else
        echo "FiraCode is already installed"
    fi

    # Check if Meslo is installed
    if [ ! -f "$FONTS_HOME/MesloGLDZNerdFont-Bold.ttf" ]; then
        wget https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.zip
        unzip Meslo.zip -d $FONTS_HOME
        rm Meslo.zip
    else
        echo "Meslo is already installed"
    fi

    # Check if FontAwesome is installed
    if [ ! -f "$FONTS_HOME/fontawesome-webfont.ttf" ]; then
        wget https://use.fontawesome.com/releases/v5.15.4/fontawesome-free-5.15.4-web.zip
        unzip fontawesome-free-5.15.4-web.zip -d $FONTS_HOME
        rm fontawesome-free-5.15.4-web.zip
    else
        echo "FontAwesome is already installed"
    fi
    cd "$current_dir"
}

install_fonts_rocky() {
    sudo dnf install fontawesome-fonts
}

install_fonts_debian() {
    sudo apt update
    sudo apt install fonts-font-awesome
}

read -p "Do you want to install fonts? (y/n): " install_fonts

if [ "$install_fonts" = "y" ] || [ "$install_fonts" = "Y" ]; then
    if [ -f /etc/arch-release ]; then
        install_fonts_arch
    elif [ -f /etc/rocky-release ]; then
        install_fonts_rocky
        install_fonts_manual
    elif [ -f /etc/debian_version ]; then
        install_fonts_debian    
        install_fonts_manual
    else
        echo "Unsupported OS"
    fi
    fc-cache -vf
else
    echo "Font installation skipped."
fi

fc-cache -vf
