#!/bin/bash

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Detect the Linux distribution
if command_exists dnf; then
    DISTRO="rocky"
elif command_exists apt-get; then
    DISTRO="debian"
elif command_exists pacman; then
    DISTRO="arch"
else
    echo "Unsupported distribution. This script works for Rocky Linux, Debian, and Arch Linux."
    exit 1
fi

# Install Hyprland and SDDM based on the detected distribution
case $DISTRO in
    rocky)
        echo "Installing Hyprland and SDDM on Rocky Linux..."
        sudo dnf copr enable solopasha/hyprland
        sudo dnf install hyprland sddm
        ;;
    debian)
        echo "Installing Hyprland and SDDM on Debian..."
        sudo apt update
        sudo apt install meson wget build-essential ninja-build cmake-extras cmake gettext gettext-base fontconfig \
        libfontconfig-dev libffi-dev libxml2-dev libdrm-dev libxkbcommon-x11-dev libxkbregistry-dev libxkbcommon-dev \
        libpixman-1-dev libudev-dev libseat-dev seatd libxcb-dri3-dev libvulkan-dev libvulkan-volk-dev vulkan-validationlayers-dev \
        libvkfft-dev libgulkan-dev libegl-dev libgles2 libegl1-mesa-dev glslang-tools libinput-bin libinput-dev libxcb-composite0-dev \
        libavutil-dev libavcodec-dev libavformat-dev libxcb-ewmh2 libxcb-ewmh-dev libxcb-present-dev libxcb-icccm4-dev \
        libxcb-render-util0-dev libxcb-res0-dev libxcb-xinput-dev sddm waybar

        current_dir=$(pwd)
        # Check if GIT_PATH is already set
        if [ -z "$GIT_PATH" ]; then
            read -p "Do you want to create a default location for git repositories? (y/n) " create_git_dir
            if [[ $create_git_dir =~ ^[Yy]$ ]]; then
                read -p "Enter the path for git repositories (default: $HOME/git): " git_path
                GIT_PATH=$git_path
                export GIT_PATH
                
                if [ ! -d "$GIT_PATH" ]; then
                    mkdir -p "$GIT_PATH"
                    echo "Created git directory at $GIT_PATH"
                else
                    echo "Git directory already exists at $GIT_PATH"
                fi
            else
                echo "Skipping git directory creation."
            fi
        else
            echo "GIT_PATH is already set to $GIT_PATH"
        fi

        cd $GIT_PATH
        git clone https://github.com/hyprwm/Hyprland
        cd Hyprland
        sudo make install
        cd $current_dir
        ;;
    arch)
        echo "Installing Hyprland, SDDM, and other packages on Arch Linux..."
        sudo pacman -S --needed hyprland xdg-desktop-portal-hyprland xorg-xwayland qt5-wayland qt6-wayland qt5ct libva \
        nwg-look rofi qt5ct jq gtk3 gtk4 xdg-desktop-portal polkit-kde-agent dunst thunar thunar-archive-plugin pamixer \
        xorg-xhost i2c-tools lxappearance pavucontrol wl-clipboard \
        waybar wl-clipboard blueman cliphist shotwell wlr-randr

        ./install_yay

        yay -S --needed swaylock-effects hyprpicker grimblast-git
        ;;
esac

echo "Hyprland and SDDM installation completed."
