#!/bin/bash

# Ask user if they want to install pciop-client
read -p "Do you want to install pciop-client, if you need it for remote work? (y/n) " install_pciop

current_dir=$(pwd)

if [[ $install_pciop =~ ^[Yy]$ ]]; then
    echo "Installing pciop-client..."
    # Function to install the latest pcoip-client for Arch Linux
    install_arch() {
        # Check if GIT_PATH is already set
        if [ -z "$GIT_PATH" ]; then
            read -p "Do you want to create a default location for git repositories? (y/n) " create_git_dir
            if [[ $create_git_dir =~ ^[Yy]$ ]]; then
                read -p "Enter the path for git repositories (default: $HOME/git): " git_path
                GIT_PATH=$git_path
                export GIT_PATH
                
                if [ ! -d "$GIT_PATH" ]; then
                    mkdir -p "$GIT_PATH"
                    echo "Created git directory at $GIT_PATH"
                else
                    echo "Git directory already exists at $GIT_PATH"
                fi
            else
                echo "Skipping git directory creation."
            fi
        else
            echo "GIT_PATH is already set to $GIT_PATH"
        fi

        cd $GIT_PATH
        git clone https://aur.archlinux.org/pcoip-client.git
        cd pcoip-client
        
        # Update PKGBUILD
        sed -i 's/23.01.1/24.03.4/' PKGBUILD
        sed -i 's/bbaf1e643e77e239968ec108e9dbee9ade17f47bb4694c8bbf97fdc229a9903f/a069189bcc5cf7c61fae6f7f88f23cc614f8d61535cce781a834c121e8df70bd/' PKGBUILD
        
        # Install dependencies
        yay -S --needed openssl-1.1 qt5-graphicaleffects qt5-networkauth qt5-quickcontrols protobuf3.12 \
        hiredis0.14 libxkbcommon-x11 libxcb xcb-util-image xcb-util-renderutil mesa
        # Build and install
        makepkg -si
        sudo setcap "cap_setgid+i" "/usr/lib/pcoip-client/usb-helper"
        sudo setcap "cap_setgid+i" "/usr/lib/pcoip-client/pcoip-client"
        # Create a symlink to the pcoip-client binary
        sudo ln -sf /usr/lib/pcoip-client/pcoip-client /usr/bin/pcoip-client

        cd "$current_dir"
    }

    # Function to install the latest pcoip-client for Rocky Linux
    install_rocky() {
        if ! rpm -q pcoip-client; then
            curl -1sLf https://dl.anyware.hp.com/xHfmOLEc9bWcllgT/pcoip-agent/cfg/setup/bash.rpm.sh | sudo -E distro=el codename=9 bash
        else
            echo "pcoip-client is already installed on Rocky Linux"
        fi
    }

    # Function to install the latest pcoip-client for Debian
    install_debian() {
        if ! dpkg -l | grep -q pcoip-client; then
            curl -1sLf https://dl.anyware.hp.com/DeAdBCiUYInHcSTy/pcoip-client/cfg/setup/bash.deb.sh | sudo -E distro=ubuntu codename=jammy bash
            sudo apt update
            cd ~/Downloads
            wget https://ftp.debian.org/debian/pool/main/p/protobuf/libprotobuf23_3.12.4-1+deb11u1_amd64.deb
            sudo apt install ./libprotobuf23_3.12.4-1+deb11u1_amd64.deb
            rm libprotobuf23_3.12.4-1+deb11u1_amd64.deb
            cd "$current_dir" 
            sudo apt update
            sudo apt install pcoip-client
            echo "pcoip-client has been installed successfully."
        else
            echo "pcoip-client is already installed on Debian"
        fi
    }

    # Detect the distribution and call the appropriate function
    if [ -f /etc/arch-release ]; then
        install_arch
    elif [ -f /etc/rocky-release ]; then
        install_rocky
    elif [ -f /etc/debian_version ]; then
        install_debian
    else
        echo "Unsupported distribution"
    fi
    
else
    echo "Skipping pciop-client installation."
fi