#!/bin/bash

# Detect the Linux distribution
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
elif type lsb_release >/dev/null 2>&1; then
    OS=$(lsb_release -si)
else
    OS=$(uname -s)
fi

# Ask user about browser installation
echo "Which browser would you like to install?"
echo "1. Thorium Browser (latest version)"
echo "2. Google Chrome"
echo "3. Firefox"
echo "4. None"
read -p "Enter your choice (1-4): " browser_choice

# Save current directory and change to Downloads folder
current_dir=$(pwd)
cd ~/Downloads

case $browser_choice in
    1)
        echo "Installing latest version of Thorium Browser..."
        case $OS in
            "Debian GNU/Linux"|"Ubuntu")
                sudo wget https://dl.thorium.rocks/debian/dists/stable/thorium.list -O /etc/apt/sources.list.d/thorium.list
                sudo apt update
                sudo apt install thorium-browser
                ;;
            "Arch Linux")
                yay -S thorium-browser-bin
                ;;
            "Rocky Linux")
                echo "Please download the latest RPM from https://github.com/Alex313031/thorium/releases"
                read -p "Press Enter after downloading the file..."
                sudo dnf install thorium-browser_*.rpm
                rm thorium-browser_*.rpm
                ;;
            *)
                echo "Unsupported OS for Thorium Browser installation. Skipping."
                ;;
        esac
        ;;
    2)
        echo "Installing Google Chrome..."
        case $OS in
            "Debian GNU/Linux"|"Ubuntu")
                wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
                sudo dpkg -i google-chrome-stable_current_amd64.deb
                sudo apt install -f
                rm google-chrome-stable_current_amd64.deb
                ;;
            "Arch Linux")
                yay -S google-chrome
                ;;
            "Rocky Linux")
                sudo dnf install https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
                ;;
            *)
                echo "Unsupported OS for Google Chrome installation. Skipping."
                ;;
        esac
        ;;
    3)
        echo "Installing Firefox..."
        case $OS in
            "Debian GNU/Linux"|"Ubuntu")
                sudo apt install firefox-esr
                ;;
            "Arch Linux")
                sudo pacman -S firefox
                ;;
            "Rocky Linux")
                sudo dnf install firefox
                ;;
            *)
                echo "Unsupported OS for Firefox installation. Skipping."
                ;;
        esac
        ;;
    4)
        echo "Skipping browser installation."
        ;;
    *)
        echo "Invalid choice. Skipping browser installation."
        ;;
esac

# Return to the original directory
cd "$current_dir"

echo "Web browser installation completed."
