#!/bin/bash

current_dir=$(pwd)
# Check if yay is installed
if ! command -v yay &> /dev/null
then
    echo "yay is not installed. Installing yay..."
    
    # Install git if not already installed
    if ! command -v git &> /dev/null
    then
        echo "Installing git..."
        sudo pacman -S --needed git
    fi

    # Clone yay repository
    # Check if GIT_PATH is already set
    if [ -z "$GIT_PATH" ]; then
        read -p "Do you want to create a default location for git repositories? (y/n) " create_git_dir
        if [[ $create_git_dir =~ ^[Yy]$ ]]; then
            read -p "Enter the path for git repositories (default: $HOME/git): " git_path
            GIT_PATH=$git_path
            export GIT_PATH
            
            if [ ! -d "$GIT_PATH" ]; then
                mkdir -p "$GIT_PATH"
                echo "Created git directory at $GIT_PATH"
            else
                echo "Git directory already exists at $GIT_PATH"
            fi
        else
            echo "Skipping git directory creation."
        fi
    else
        echo "GIT_PATH is already set to $GIT_PATH"
    fi
    cd $GIT_PATH
    git clone https://aur.archlinux.org/yay.git 
    
    # Navigate to yay directory
    cd yay
    
    # Build and install yay
    makepkg -si 
    cd $current_dir
    
    echo "yay has been installed successfully."
else
    echo "yay is already installed."
fi
