#! /bin/bash

get_git_path() {
    # Check if GIT_PATH is already set
    if [ -z "$GIT_PATH" ]; then
        read -p "Do you want to create a default location for git repositories? (y/n) " create_git_dir
        if [[ $create_git_dir =~ ^[Yy]$ ]]; then
            read -p "Enter the path for git repositories (default: $HOME/git): " git_path
            GIT_PATH=$git_path
            export GIT_PATH
            
            if [ ! -d "$GIT_PATH" ]; then
                mkdir -p "$GIT_PATH"
                echo "Created git directory at $GIT_PATH"
            else
                echo "Git directory already exists at $GIT_PATH"
            fi
        else
            echo "Skipping git directory creation."
        fi
    else
        echo "GIT_PATH is already set to $GIT_PATH"
    fi
}

get_git_path

current_dir=$(pwd)

# Ask user if they want to install and setup dwm-curado
read -p "Do you want to install and setup dwm-curado, a fork of dwm-titus? (y/n) " install_dwm_curado

if [[ $install_dwm_curado =~ ^[Yy]$ ]]; then

    # Detect the operating system
    if [ -f /etc/arch-release ]; then
        # Arch Linux
        sudo pacman -S pavucontrol
    elif [ -f /etc/debian_version ]; then
        # Debian/Ubuntu
        sudo apt install pavucontrol
    else
        echo "Unsupported operating system. Please install Starship manually."
        exit 1
    fi

    echo "Installing and setting up dwm-curado..."
    git clone https://github.com/curadotd/dwm-curado.git $GIT_PATH/dwm-curado
    cd $GIT_PATH/dwm-curado
    ./setup
    cd $current_dir
    # Add any additional configuration steps
else
    echo "Skipping dwm-curado installation and setup."
    exit 0
fi
