#!/bin/bash

FONTS_HOME=$HOME/.local/share/fonts
if [ ! -d "$FONTS_HOME" ]; then
    mkdir -p "$FONTS_HOME"
fi

current_dir=$(pwd)

install_fonts_arch() {
    sudo pacman -S ttf-fira-code ttf-meslo-nerd ttf-font-awesome ttf-firacode-nerd otf-font-awesome --needed
    ./install_yay

    yay -S --needed ttf-comfortaa ttf-icomoon-feather ttf-icomoon-feather tela-icon-theme nordzy-icon-theme otf-sora
}

install_fonts_manual() {
    cd ~/Downloads
    # Check if FiraCode is installed
    if [ ! -f "$FONTS_HOME/FiraCode-Regular.ttf" ]; then
        wget https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip
        unzip FiraCode.zip -d $FONTS_HOME
        rm FiraCode.zip
    else
        echo "FiraCode is already installed"
    fi

    # Check if Meslo is installed
    if [ ! -f "$FONTS_HOME/MesloGLDZNerdFont-Bold.ttf" ]; then
        wget https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.zip
        unzip Meslo.zip -d $FONTS_HOME
        rm Meslo.zip
    else
        echo "Meslo is already installed"
    fi

    # Check if FontAwesome is installed
    if [ ! -f "$FONTS_HOME/fontawesome-webfont.ttf" ]; then
        wget https://use.fontawesome.com/releases/v5.15.4/fontawesome-free-5.15.4-web.zip
        unzip fontawesome-free-5.15.4-web.zip -d $FONTS_HOME
        rm fontawesome-free-5.15.4-web.zip
    else
        echo "FontAwesome is already installed"
    fi
    cd "$current_dir"
}

install_fonts_rocky() {
    sudo dnf install fontawesome-fonts
}

install_fonts_debian() {
    sudo apt update
    sudo apt install fonts-font-awesome
}

read -p "Do you want to install fonts? (y/n): " install_fonts

if [ "$install_fonts" = "y" ] || [ "$install_fonts" = "Y" ]; then
    if [ -f /etc/arch-release ]; then
        install_fonts_arch
        fc-cache -vf
    elif [ -f /etc/rocky-release ]; then
        install_fonts_rocky
        install_fonts_manual
        fc-cache -vf
    elif [ -f /etc/debian_version ]; then
        install_fonts_debian    
        install_fonts_manual
        fc-cache -vf
    else
        echo "Unsupported OS"
    fi
else
    echo "Font installation skipped."
    exit 0
fi

echo "Font installation completed."
