#!/bin/bash

echo "Do you want to install the MATE desktop environment? (y/n)"
read -r install_mate

if [[ $install_mate =~ ^[Yy]$ ]]; then
    # Determine the operating system
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$NAME
    elif type lsb_release >/dev/null 2>&1; then
        OS=$(lsb_release -si | grep -v "No LSB modules are available." | head -n1)
    else
        OS=$(uname -s)
    fi  

    case $OS in
        "Rocky Linux")
            sudo dnf install NetworkManager-adsl NetworkManager-bluetooth NetworkManager-libreswan-gnome \
            NetworkManager-openvpn-gnome NetworkManager-ovs NetworkManager-ppp NetworkManager-team NetworkManager-wifi \
            NetworkManager-wwan adwaita-gtk2-theme alsa-plugins-pulseaudio atril atril-caja atril-thumbnailer caja \
            caja-actions caja-image-converter caja-open-terminal caja-sendto caja-wallpaper caja-xattr-tags \
            dconf-editor engrampa eom firewall-config gnome-disk-utility gnome-epub-thumbnailer \
            gstreamer1-plugins-ugly-free gtk2-engines gucharmap gvfs-fuse gvfs-gphoto2 gvfs-mtp gvfs-smb \
            initial-setup-gui libmatekbd libmatemixer libmateweather libsecret lm_sensors marco mate-applets \
            mate-backgrounds mate-calc mate-control-center mate-desktop mate-dictionary mate-disk-usage-analyzer \
            mate-icon-theme mate-media mate-menus mate-menus-preferences-category-menu mate-notification-daemon \
            mate-panel mate-polkit mate-power-manager mate-screensaver mate-screenshot mate-search-tool \
            mate-session-manager mate-settings-daemon mate-system-log mate-system-monitor mate-terminal \
            mate-themes mate-user-admin mate-user-guide mozo network-manager-applet nm-connection-editor \
            p7zip p7zip-plugins pluma seahorse seahorse-caja xdg-user-dirs-gtk
            ;;
        "Debian GNU/Linux" | "Ubuntu")
            sudo apt update
            sudo apt install task-mate-desktop
            ;;
        "Arch Linux")
            sudo pacman -Syu
            sudo pacman -S mate mate-extra --needed
            ;;
        *)
            echo "Unsupported operating system: $OS"
            exit 1
            ;;
    esac

    echo "MATE desktop environment has been installed. Please reboot your system to apply changes."
else
    echo "MATE desktop installation skipped."
fi
