#!/bin/bash

echo "Select Display Manager to install:"
echo "1) SDDM"
echo "2) LightDM"
echo "3) Skip"
read -p "Enter your choice (1): " choice

current_dir=$(pwd)

get_git_path() {
    # Check if GIT_PATH is already set
    if [ -z "$GIT_PATH" ]; then
        read -p "Enter the path for git repositories (default: $HOME/git): " git_path
        GIT_PATH=${git_path:-$HOME/git}
        export GIT_PATH

        if [ ! -d "$GIT_PATH" ]; then
            mkdir -p "$GIT_PATH"
            echo "Created git directory at $GIT_PATH"
        else
            echo "Git directory already exists at $GIT_PATH"
        fi
    else
        echo "GIT_PATH is already set to $GIT_PATH"
    fi
}

if [[ $choice -eq 1 ]]; then
    read -p "Do you want to install and set up the Tokyo Night theme for SDDM? (y/n): " install_theme
    if [[ $install_theme == "y" ]]; then
        get_git_path
        cd $GIT_PATH
        git clone https://github.com/rototrash/tokyo-night-sddm.git
        # Check if the themes directory exists, create it if not
        sudo mkdir -p /usr/share/sddm/themes/
        sudo cp -R tokyo-night-sddm /usr/share/sddm/themes/
        echo "Tokyo Night theme installed. Please configure it in /etc/sddm.conf."
    fi
fi

cd $current_dir

if [[ $choice -eq 1 ]]; then
    sudo dnf install epel-release
    sudo dnf install sddm
    sudo systemctl enable sddm
    sudo systemctl set-default graphical.target
elif [[ $choice -eq 2 ]]; then
    sudo dnf install epel-release
    sudo dnf install lightdm lightdm-gtk
    sudo systemctl enable lightdm
    sudo systemctl set-default graphical.target
elif [[ $choice -eq 3 ]]; then
    echo "Skipping display manager installation."
    exit 0
else
    echo "Invalid choice"
    exit 1
fi

echo "Installation complete."
