#!/bin/bash

export PATH=$PATH:$HOME/.local/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib
export INCLUDE_PATH=$INCLUDE_PATH:$HOME/.local/include

# Install dependencies
sudo dnf groupinstall "Development Tools"
sudo dnf install epel-release
sudo dnf config-manager --set-enabled crb
sudo dnf install cmake git python3 python3-pip doxygen python3-pyopengl libXt-devel ncurses-compat-libs
pip install PySide6 PyOpenGL

# Clone and build OpenUSD
git clone https://github.com/PixarAnimationStudios/OpenUSD.git
cd OpenUSD
python3 build_scripts/build_usd.py --ptex \
--openvdb --prman --prman-location /mnt/repository/software/install/linux/pixar/RenderManProServer-25.2 \
--openimageio --opencolorio  --alembic --hdf5 --materialx /mnt/repository/software/install/linux/pixar/OpenUSD

echo "OpenUSD installation completed."
