#!/bin/bash

echo "Do you want to install the MATE desktop environment? (y/n)"
read -r install_mate

if [[ $install_mate =~ ^[Yy]$ ]]; then
    sudo apt update
    sudo apt install task-mate-desktop

    echo "MATE desktop environment has been installed. Please reboot your system to apply changes."
else
    echo "MATE desktop installation skipped."
fi
