#!/bin/bash

FILE="thinlinc-client_*_amd64.deb"

# Ask the user to download the file
echo "Please download the ThinLinc client file from:"
echo "https://www.cendio.com/thinlinc/download/"
echo "and save it to your $HOME/Downloads folder."
echo "Press Enter when you have completed this step."
read -p ""

# Check if the file exists
if [ -z "$(ls $HOME/Downloads/$FILE 2>/dev/null)" ]; then
    echo "File not found in $HOME/Downloads. Exiting."
    exit 1
fi

# Set the actual filename for later use
ACTUAL_FILE=$(ls $HOME/Downloads/$FILE | head -n 1)

sudo apt install "$ACTUAL_FILE"

echo "ThinLinc client installation completed."
