#!/bin/bash

# Function to install dependencies for Debian
install_debian_dependencies() {
    sudo apt update
    sudo apt install libssl-dev ocl-icd-opencl-dev fakeroot xorriso libapr1 libaprutil1 \
    libxcb-xinput0 libxcb-xinerama0 libxcb-keysyms1 libxcb-icccm4 libxcb-cursor0 \
    libxcb-render-util0 libxcb-image0 libxcb-composite0
}

# Function to install graphics drivers and dependencies
install_debian_graphics() {
    local gpu_type=$1

    case $gpu_type in
        nvidia)
            sudo apt install nvidia-driver nvidia-opencl-icd libglu1-mesa libgstreamer-plugins-bad1.0-0
            ;;
        amd)
            sudo apt install mesa-opencl-icd
            ;;
        intel)
            sudo apt install intel-opencl-icd
            ;;
        *)
            echo "Unsupported GPU type. Please install graphics drivers manually."
            ;;
    esac
}

# Ask user if they want to install DaVinci Resolve
read -p "Do you want to install DaVinci Resolve for Linux? (y/n): " install_resolve

if [[ $install_resolve =~ ^[Yy]$ ]]; then
    echo "Debian system detected. Installing dependencies..."
    install_debian_dependencies
    echo "Please select your GPU type (nvidia/amd/intel):"
    read gpu_type
    install_debian_graphics $gpu_type

    echo "Please download DaVinci Resolve from https://www.blackmagicdesign.com/products/davinciresolve"
    echo "Save the file in your $HOME/Downloads directory."
    read -p "Press Enter when you have completed the download."

    read -p "Enter the name of the downloaded file: " resolve_file

    if [ ! -f "$HOME/Downloads/$resolve_file" ]; then
        echo "File not found. Please make sure you entered the correct filename."
        exit 1
    fi

    echo "Extracting the installer..."
    cd "$HOME/Downloads"
    unzip "$resolve_file"

    run_file=$(find . -name "*.run" -type f)
    if [ -z "$run_file" ]; then
        echo "Could not find the .run file. Installation failed."
        exit 1
    fi

    echo "Running the installer..."
    chmod +x "$run_file"
    sudo SKIP_PACKAGE_CHECK=1 ./$run_file

    echo "Fixing dependencies for Debian-based system..."
    # Array with library names
    libraries=(
    "libglib-2.0.so.0"
    "libgobject-2.0.so.0"
    "libgstreamer-1.0.so.0"
    "libgstsdp-1.0.so.0"
    "libgstwebrtc-1.0.so.0"
    "libgio-2.0.so.0"
    "libgmodule-2.0.so.0"
    "libgstrtp-1.0.so.0"
    "libgstpbutils-1.0.so.0"
    "libgstbase-1.0.so.0"
    "libgstvideo-1.0.so.0"
    "libgstaudio-1.0.so.0"
    "libgsttag-1.0.so.0"
    "liborc-0.4.so.0"
    )

    # Loop to create symbolic links
    for lib in "${libraries[@]}"; do
        sudo ln -sf "/usr/lib/x86_64-linux-gnu/$lib" /opt/resolve/libs/
    done

    echo "DaVinci Resolve installation completed."
else
    echo "Skipping DaVinci Resolve installation."
fi
