#!/bin/bash

echo "Do you want to install OBS Studio? (y/n)"
read -r response

if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    echo "Installing OBS Studio..."
    sudo pacman -S --needed obs-studio ffmpeg
    echo "OBS Studio installation complete."
else
    echo "OBS Studio installation skipped."
fi
