#!/bin/bash

# Ask user if they want to install pcoip-client
read -p "Do you want to install pcoip-client, if you need it for remote work? (y/n) " install_pcoip

current_dir=$(pwd)

if [[ $install_pcoip =~ ^[Yy]$ ]]; then
    echo "Installing pcoip-client..."

    # Check if GIT_PATH is already set
    if [ -z "$GIT_PATH" ]; then
        read -p "Enter the path for git repositories (default: $HOME/git): " git_path
        GIT_PATH=${git_path:-$HOME/git}
        export GIT_PATH

        if [ ! -d "$GIT_PATH" ]; then
            mkdir -p "$GIT_PATH"
            echo "Created git directory at $GIT_PATH"
        else
            echo "Git directory already exists at $GIT_PATH"
        fi
    else
        echo "GIT_PATH is already set to $GIT_PATH"
    fi

    cd $GIT_PATH
    git clone https://aur.archlinux.org/pcoip-client.git
    cd pcoip-client

    # Update PKGBUILD to a newer client release if the AUR package is behind.
    # Check https://anyware.hp.com/find/product/hp-anyware for the latest version.
    sed -i 's/23.01.1/24.03.4/' PKGBUILD
    sed -i 's/bbaf1e643e77e239968ec108e9dbee9ade17f47bb4694c8bbf97fdc229a9903f/a069189bcc5cf7c61fae6f7f88f23cc614f8d61535cce781a834c121e8df70bd/' PKGBUILD

    # Install dependencies
    yay -S --needed openssl-1.1 qt5-graphicaleffects qt5-networkauth qt5-quickcontrols protobuf3.12 \
    hiredis0.14 libxkbcommon-x11 libxcb xcb-util-image xcb-util-renderutil mesa
    # Build and install
    makepkg -si
    sudo setcap "cap_setgid+i" "/usr/lib/pcoip-client/usb-helper"
    sudo setcap "cap_setgid+i" "/usr/lib/pcoip-client/pcoip-client"
    # Create a symlink to the pcoip-client binary
    sudo ln -sf /usr/lib/pcoip-client/pcoip-client /usr/bin/pcoip-client

    cd "$current_dir"
else
    echo "Skipping pcoip-client installation."
fi
