#!/bin/bash

# Ask user if they want to compile and install OpenRV
read -p "Do you want to compile and install OpenRV? (y/n) " install_openrv

current_dir=$(pwd)

if [[ $install_openrv =~ ^[Yy]$ ]]; then

    #Add some envs
    export PIP_BREAK_SYSTEM_PACKAGES=1
    read -p "Please enter the path where you have installed Qt (e.g., /mnt/repository/software/install/linux/Qt/5.15.2/gcc_64): " qt_home
    export QT_HOME="$qt_home"
    read -p "Please enter the installation path for OpenRV (e.g., /mnt/repository/software/install/linux/ASF/rv): " rv_inst
    export RV_INST="$rv_inst"

    # Install dependencies
    sudo pacman -Syu
    sudo pacman -S --needed alsa-lib autoconf automake avahi bison bzip2 cmake curl flex gcc \
    libxcomposite libxi libaio libffi nasm ncurses nss libtool xkeyboard-config \
    libxdamage libxrandr libxtst libxcursor mesa meson ninja openssl patch perl glib2 ocl-icd \
    opencl-headers python qt5-base readline sqlite tcl tcsh tk yasm zip zlib glu pre-commit

    # Clone the OpenRV repository
    git clone --recursive https://github.com/AcademySoftwareFoundation/OpenRV.git
    cd OpenRV || exit

    # Bootstrap, build, and install OpenRV
    pre-commit install
    python3 -m pip install -r requirements.txt

    source rvcmds.sh
    rvsetup
    rvcfg -DRV_FFMPEG_NON_FREE_DECODERS_TO_ENABLE="aac;hevc" -DRV_FFMPEG_NON_FREE_ENCODERS_TO_ENABLE="aac"

    echo "OpenRV installation completed."
else
    echo "Skipping OpenRV compile and install"
fi
