#!/bin/bash

FILE="tl-*-client-linux-dynamic-x86_64.tar.gz"

# Ask the user to download the file
echo "Please download the ThinLinc client file from:"
echo "https://www.cendio.com/thinlinc/download/"
echo "and save it to your $HOME/Downloads folder."
echo "Press Enter when you have completed this step."
read -p ""

# Check if the file exists
if [ -z "$(ls $HOME/Downloads/$FILE 2>/dev/null)" ]; then
    echo "File not found in $HOME/Downloads. Exiting."
    exit 1
fi

# Set the actual filename for later use
ACTUAL_FILE=$(ls $HOME/Downloads/$FILE | head -n 1)

sudo mkdir -p /opt/thinlinc_client
sudo tar -xzf "$ACTUAL_FILE" -C /opt/thinlinc_client --strip-components=1

# Create a desktop entry
mkdir -p ~/.local/share/applications
cat << EOF > ~/.local/share/applications/thinlinc_client.desktop
[Desktop Entry]
Name=ThinlincClient
Exec=/opt/thinlinc_client/bin/tlclient
Icon=/opt/thinlinc_client/lib/tlclient/thinlinc_16.png
Type=Application
Categories=Development;
EOF

echo "ThinLinc client installation completed."
