#!/bin/bash

echo "Do you want to install the MATE desktop environment? (y/n)"
read -r install_mate

if [[ $install_mate =~ ^[Yy]$ ]]; then
    sudo pacman -Syu
    sudo pacman -S --needed mate mate-extra

    echo "MATE desktop environment has been installed. Please reboot your system to apply changes."
else
    echo "MATE desktop installation skipped."
fi
