#!/bin/bash

# Function to check if a command is available
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check if git is installed, if not, install it
if ! command_exists git; then
    echo "Git is not installed. Attempting to install Git..."
    sudo pacman -Sy --needed git vim

    if command_exists git; then
        echo "Git has been successfully installed."
    else
        echo "Failed to install Git. Please install it manually and run this script again."
        exit 1
    fi
fi

# Check if gh is installed, if not, install it
if ! command_exists gh; then
    echo "GitHub CLI (gh) is not installed. Attempting to install GitHub CLI..."
    sudo pacman -Sy --needed github-cli vim
    if command_exists yay; then
        yay -S --needed git-completion
    fi

    if command_exists gh; then
        echo "GitHub CLI has been successfully installed."
    else
        echo "Failed to install GitHub CLI. Please install it manually and run this script again."
        exit 1
    fi
fi

# Set up Git user User Name
read -p 'Enter your Git username "Mona Lisa" :' git_user
git config --global user.name "$git_user"
echo "Git username set to: $git_user"

# Set up Git user email
read -p 'Enter your Git user email "YOUR_EMAIL" :' git_email
git config --global user.email "$git_email"
echo "Git user email set to: $git_email"

# use vim as the code editor
git config --global core.editor "vim"

# Log in with GitHub CLI
echo "Logging in to GitHub with gh CLI..."
gh auth login

echo "Git and GitHub setup complete!"
