#!/bin/bash

# On Arch, environment variables are set through a profile.d script.
qt_conf_path="/etc/profile.d/qt.sh"

# Create qt.sh if it doesn't exist
if [ ! -f "$qt_conf_path" ]; then
    sudo tee "$qt_conf_path" > /dev/null << EOL
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_QPA_PLATFORM="xcb"
export QT_STYLE_OVERRIDE="kvantum"
export QT_AUTO_SCREEN_SCALE_FACTOR=1
EOL
    echo "Created $qt_conf_path"
else
    echo "$(basename "$qt_conf_path") already exists. Skipping creation."
fi
