#!/bin/bash

qt_conf_path="/etc/environment.d/qt.conf"

# Create qt.conf if it doesn't exist
if [ ! -f "$qt_conf_path" ]; then
    sudo mkdir -p /etc/environment.d
    sudo tee "$qt_conf_path" > /dev/null << EOL
QT_QPA_PLATFORMTHEME=qt5ct
QT_QPA_PLATFORM="xcb"
QT_STYLE_OVERRIDE="kvantum"
QT_AUTO_SCREEN_SCALE_FACTOR=1
EOL
    echo "Created $qt_conf_path"
else
    echo "$(basename "$qt_conf_path") already exists. Skipping creation."
fi
